# Generated by Django 5.0.6 on 2024-06-04 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api_books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='number_of_pages',
            field=models.IntegerField(default=220),
            preserve_default=False,
        ),
    ]
