# Generated by Django 5.0.6 on 2024-06-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api_books', '0003_alter_books_number_of_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='year_of_publication',
            field=models.IntegerField(default=2012, max_length=6),
            preserve_default=False,
        ),
    ]
