# Generated by Django 5.0.6 on 2024-06-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api_books', '0005_alter_books_year_of_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='number_of_pages',
            field=models.IntegerField(),
        ),
    ]
